### ISSUE TITLE
SVG's won't appear

### ISSUE THREAD

**Issue by paulzobs** [paulzobs/Zobs-Paul-Portfolio#2]
I have a few SVG's in a footer on profile page that won't appear.  
@wendywarren

**Comment by wendywarren** [comment]
Hey @paulzobs!

There doesn't seem to be any deployments for this repo where it looks like you've been working so I'm not able to see the issue you're having but I can download the files and look into it locally on my computer. I'll get back to you shortly about the svg's.

Keep in mind you need to be using this repo to submit because it has the markbot file within it : https://github.com/paulzobs/web-design-2-independent-project.

Let me know if you need any help fixing up your other repo so you can submit.

Wendy

**Comment by wendywarren** [comment]
I took a look and what you have to display the svg's in your code is correct. The one thing with using svg spritesheets with `xlink:href="images/icons.svg#instagram"` is that you can't see the svg locally but you will be able to see it once it's on a server (on github). 

Let's get you up and running over on your other repo. I'm pretty sure the svgs will display for you once you can view it online.

Wendy
